Structure languages
PlaceOS/docs pull request #77
Opened 2021-05-24 11:15 UTC by jeremyw24

This PR:

* Moves Typescript under a Languages sub-category in the overview section.
* Adds Crystal Lang Overview
* Adds spider-gazelle section to Crytal

2021-05-24 11:30 UTC, kimburgess requested changes
`overview/Languages` -> `overview/languages`: for consistency, would be good to keep the directory tree downcased.

I'd also suggest that Spider-Gazelle can be omitted from here. Two reasons for this:
1. It's a framework, not a language.
2. It is not something that related to usage of PlaceOS, or any user extensible parts of the platform.

It is generally useful, but has it's own documentation site for that purpose. Inclusion here just adds noise.

2021-05-24 12:40 UTC, jeremyw24 commented
@kimburgess there is a bug here where downcasing the directory causes said directoy to appear in the navigation tree in lowercase.

Setting the folder name with uppercase `Languages` will cause it to display correctly in the navigation tree.

I have just amended to lowercase `languages` while removing spider-gazelle content and confirmed the above observation to be correct.

For aesthetics, I will uppercase the directory again so we can proceed with this PR. Suspect this needs to be raised as a bug against docusaurs? 

From `_category_.yml`

```
label: Languages
position: 1
collapsed: false
```

Noting this is ignored. 

![image](https://user-images.githubusercontent.com/4019090/119348917-d4928380-bce0-11eb-9f67-26746373438e.png)

2021-05-24 12:43 UTC, kimburgess commented
Looks like you're missing a trailing underscore on that [`_categeory_.yml`](https://github.com/PlaceOS/docs/blob/16d991643539a44ccade4878f2ecc446e0424235/overview/Laguages/_category.yml) so it's being ignored at the moment. Default behaviour without that is to just use the directory name.

2021-05-25 04:21 UTC, jeremyw24 reviewed
Changes have been made.

2021-05-25 04:22 UTC, merged